{% set name = "unrar" %}
{% set version = "7.0.9" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  fn: "{{ name|lower }}-{{ version }}.tar.gz"
  url: "https://www.rarlab.com/rar/unrarsrc-{{ version }}.tar.gz"
  sha256: "505c13f9e4c54c01546f2e29b2fcc2d7fabc856a060b81e5cdfe6012a9198326"
  patches:
    - patches/0001-makefile.patch   # [not win]

build:
  number: 0
  skip: True    # [win]

requirements:
  build:
    - {{ compiler("cxx") }}
    - make      # [not win]

test:
  commands:
    - unrar

extra:
  home: https://www.rarlab.com/
  license: LicenseRef-Freeware
  license_file: license.txt
  summary: Unarchiver for .rar files (non-free)
  dev_url: https://www.rarlab.com/rar_add.htm

extra:
  recipe-maintainers:
    - chenghlee
